import base64
import logging
import os

import requests

logger = logging.getLogger(__name__)


def _post(url: str, payload: dict) -> None:
    api_key = os.environ["MAILER_API_KEY"]
    response = requests.post(url, params={"api_key": api_key}, json=payload, timeout=30)

    logger.debug(f"Apps Script response {response.status_code}: {response.text[:200]}")

    if not response.ok:
        raise Exception(f"Mailer HTTP {response.status_code}: {response.text[:200]}")

    # Apps Script may return empty body or JSON — both are acceptable
    if response.text.strip():
        try:
            result = response.json()
            if not result.get("success"):
                raise Exception(f"Mailer failed: {result.get('error')}")
        except requests.exceptions.JSONDecodeError:
            logger.warning(f"Apps Script returned non-JSON response: {response.text[:200]}")


def send_invoice_email(
    xlsx_bytes: bytes,
    recipients: list[str],
    all_results: list,
    errors: list[str] | None = None,
) -> None:
    po_count        = len(all_results)
    line_item_count = sum(len(r.get("line_items", [])) for r in all_results)

    po_lines = [
        f"PO {r.get('invoice_number', 'Unknown')} — {len(r.get('line_items', []))} item(s)"
        for r in all_results
    ]

    summary = (
        f"{po_count} POs | {line_item_count} line items\n" + "\n".join(po_lines)
    )

    error_section = ""
    if errors:
        items_html = "".join(f"<li>{e}</li>" for e in errors)
        error_section = f"<p><b>Partial failures:</b><ul>{items_html}</ul></p>"

    payload = {
        "to":       recipients,
        "subject":  f"E-Invoices Ready — {po_count} POs, {line_item_count} Line Items",
        "body": f"""
            <h3>Your E-Invoice file is ready</h3>
            <p><b>{po_count}</b> POs processed with <b>{line_item_count}</b> line items.</p>
            {error_section}
            <p>The XLSX file is attached — upload it directly to the GST portal.</p>
            <br/>
            <p style="color: grey; font-size: 12px;">Generated by BTM Finance Tool</p>
        """,
        "file":     base64.b64encode(xlsx_bytes).decode("utf-8"),
        "filename": "e_invoices.xlsx",
        "summary":  summary,
    }

    _post(os.environ["APPS_SCRIPT_URL"], payload)
    logger.info(f"Email sent to {recipients} — {summary.splitlines()[0]}")


def send_error_email(recipients: list[str], errors: list[str]) -> None:
    items = "".join(f"<li>{e}</li>" for e in errors)

    payload = {
        "to":      recipients,
        "subject": "E-Invoice Processing Failed",
        "body": f"""
            <h3>E-Invoice Processing Failed</h3>
            <p>All uploaded files failed to process:</p>
            <ul>{items}</ul>
            <p>Please check the files and try again.</p>
            <br/>
            <p style="color: grey; font-size: 12px;">Generated by BTM Finance Tool</p>
        """,
    }

    _post(os.environ["APPS_SCRIPT_URL"], payload)
    logger.info(f"Error email sent to {recipients}")
