NUMBER_FIELDS = {
    "tax_rate", "quantity", "unit_price",
    "party_pincode", "dispatch_pincode", "ship_to_pincode",
    "transport_distance",
}

HEADERS = ["col_letter", "field_name", "datatype", "source", "hardcoded_value", "description", "mandatory"]

FIELD_CONFIG = [
    ("B",  "supply_type",                      "dropdown", "hardcoded", "B2B",                    "GST supply type",                                                                 "Yes"),
    ("C",  "doc_type",                          "dropdown", "hardcoded", "Tax Invoice",            "Document type",                                                                   "Yes"),
    ("D",  "invoice_number",                    "string",   "extracted", "",                       "The PO number exactly as printed, e.g. 1736010047195",                            "Yes"),
    ("E",  "invoice_date",                      "date",     "extracted", "",                       "Date of the PO formatted as DD/MM/YYYY",                                          "Yes"),
    ("F",  "transaction_type",                  "dropdown", "hardcoded", "Combination of 2 and 3", "Billing and shipping structure",                                                  "Yes"),
    ("G",  "Party Address As  Billing Address", "dropdown", "hardcoded", "Yes",                   "Is the party address same as the billing address",                                "Yes"),
    ("H",  "party_gstin",                       "string",   "extracted", "",                       "GSTIN of the buyer — the Delivered To party e.g. 29AAFCG9846E1Z7",                "Yes"),
    ("I",  "party_trade_name",                  "string",   "extracted", "",                       "The company BTM is raising this invoice ON — the buyer, not the seller",          "Yes"),
    ("J",  "party_legal_name",                  "string",   "extracted", "",                       "Copy the exact same value as party_trade_name",                                   "Yes"),
    ("K",  "party_address1",                    "string",   "extracted", "",                       "First line of Delivered To address only — exclude city, state, and pincode",      "Yes"),
    ("L",  "party_location",                    "string",   "extracted", "",                       "City name only from the Delivered To address",                                    "Yes"),
    ("M",  "party_pincode",                     "number",   "extracted", "",                       "6 digit pincode from the Delivered To address",                                   "Yes"),
    ("N",  "party_state",                       "dropdown", "derived",   "",                       "State name only from Delivered To address e.g. Karnataka — code added by system", "Yes"),
    ("T",  "product_description",               "string",   "extracted", "",                       "Full product name exactly as printed in the line item",                           "Yes"),
    ("U",  "is_service",                        "dropdown", "hardcoded", "No",                     "Products not services",                                                           "Yes"),
    ("V",  "hsn_code",                          "string",   "extracted", "",                       "HSN code from the line item e.g. 33049910",                                       "Yes"),
    ("W",  "quantity",                          "number",   "extracted", "",                       "Quantity ordered for this specific line item as a plain number",                   "Yes"),
    ("Y",  "unit",                              "dropdown", "hardcoded", "PCS-PIECES",             "Unit of measurement",                                                             "Yes"),
    ("Z",  "unit_price",                        "number",   "extracted", "",                       "Basic Cost Price of the product — pre-tax, NOT the landing rate or MRP",          "Yes"),
    ("AA", "tax_rate",                          "number",   "hardcoded", "18",                     "IGST percentage",                                                                 "Yes"),
    ("BB", "party_address2",                    "string",   "derived",   "",                       "Leave empty — derived from party_address1 by system",                             "Yes"),
    ("BD", "dispatch_gstin",                    "string",   "extracted", "",                       "GSTIN of the Delivered By party — the seller/vendor e.g. 36AALCB0248H1ZR",        "Yes"),
    ("BE", "transporter_name",                  "string",   "extracted", "",                       "Name of the transporter if mentioned in the PO, else return empty string",        "No"),
    ("BF", "transport_mode",                    "dropdown", "hardcoded", "Road",                   "Mode of transport",                                                               "No"),
    ("BG", "transport_distance",                "number",   "extracted", "",                       "Distance in KM if mentioned in the PO, else return empty string",                 "No"),
    ("BH", "eway_doc_no",                       "string",   "extracted", "",                       "Copy the exact same value as invoice_number",                                     "No"),
    ("BI", "eway_date",                         "date",     "extracted", "",                       "Copy the exact same value as invoice_date",                                       "No"),
    ("BJ", "vehicle_number",                    "string",   "extracted", "",                       "Vehicle number if mentioned in the PO, else return empty string",                 "No"),
    ("BR", "ship_to_gstin",                     "string",   "derived",   "",                       "Copied from party_gstin by system",                                               "Yes"),
    ("BS", "ship_to_trade_name",                "string",   "extracted", "",                       "Company name of the Delivered To party — the buyer",                              "Yes"),
    ("BT", "ship_to_name",                      "string",   "extracted", "",                       "Copy the exact same value as ship_to_trade_name",                                 "Yes"),
    ("BU", "ship_to_location",                  "string",   "extracted", "",                       "City name only from the Delivered To address",                                    "Yes"),
    ("BV", "ship_to_pincode",                   "number",   "extracted", "",                       "6 digit pincode from the Delivered To address",                                   "Yes"),
    ("BW", "ship_to_state",                     "dropdown", "derived",   "",                       "State name only from Delivered To address e.g. Karnataka — code added by system", "Yes"),
    ("BZ", "ship_to_address1",                  "string",   "extracted", "",                       "First line of Delivered To address only — exclude city, state, and pincode",      "Yes"),
    ("CA", "ship_to_address2",                  "string",   "derived",   "",                       "Leave empty — derived from ship_to_address1 by system",                           "Yes"),
    ("DI", "vendor_po_ref_no",                  "string",   "extracted", "",                       "Copy the exact same value as invoice_number",                                     "Yes"),
    ("DJ", "vendor_po_ref_date",                "date",     "extracted", "",                       "Copy the exact same value as invoice_date",                                       "Yes"),
]
